name       : libksane
version    : 18.08.2
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/libksane-18.08.2.tar.xz : 0a1f2e5872cb3b36d75dfe4501d78133b82aab098179284f3b0cff2a7e63edbf
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - kconfig-devel
    - ki18n-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
