name       : libksane
version    : 21.04.2
release    : 40
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/libksane-21.04.2.tar.xz : c20eac11af76bf8655abc5a06764c5b9b5e21724e89f37f08c30b967393bdd65
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - kconfig-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
