name       : libksane
version    : 21.08.3
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/libksane-21.08.3.tar.xz : dea5b9432957e084fb7c7168b8bf77c14514aee8d922845484b156755bcbdf20
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - kconfig-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
