name       : libksane
version    : 21.12.1
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/libksane-21.12.1.tar.xz : 9ddbff9aaecb74a84cf740b4031ecfc20693d1a0fceb21ce8d331bd325018cca
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - kconfig-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
