name       : libksane
version    : 19.04.1
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.1/src/libksane-19.04.1.tar.xz : c89039afa641640cbc65b01ae735ee9b70bd3283095d6b034665ddb048d33417
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - kconfig-devel
    - ki18n-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
