name       : libksane
version    : 19.04.3
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.3/src/libksane-19.04.3.tar.xz : ec9c0a969806fefcefc0fda2e227bf0908e2b338fdf3377870a910d7f041e1e0
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - kconfig-devel
    - ki18n-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
