name       : libksane
version    : 22.04.1
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/libksane-22.04.1.tar.xz : bb755d27682b0a0f4b23af8267165822bf5cad09c03cf24429d8f8b23b226480
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - kconfig-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
