name       : libksane
version    : 22.04.2
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/libksane-22.04.2.tar.xz : 37ac1358d19e062eec782de31632885abd203eec0dade8f0c13f2f720e6c40b3
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - kconfig-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
