name       : libksane
version    : 20.04.3
release    : 28
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.3/src/libksane-20.04.3.tar.xz : 34827bcc5b9277292dd4434f2bf7610a28d54c86565f0410d4470c61f374c46e
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - kconfig-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
