name       : libksane
version    : 23.04.0
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/libksane-23.04.0.tar.xz : 9e0d6e9afc34b09fe40144c289638a373955d7ecf533c07b83629b9c1daec75e
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - kconfig-devel
    - ksanecore-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
