name       : libksane
version    : 20.12.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/libksane-20.12.2.tar.xz : 8bf0a7ffb4e7d98b5381e958cf17733163bffa64e3bfe79e82e48be6bc761cae
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - kconfig-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
