name       : libksane
version    : 19.04.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.0/src/libksane-19.04.0.tar.xz : 15a4f14ddb26e7e0ed54926c54941b29eebba1fabb2e75ad9f5cd48b9b673f58
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - kconfig-devel
    - ki18n-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
