name       : libksane
version    : 19.08.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.0/src/libksane-19.08.0.tar.xz : 62c670c316a47facbd0beedb0fcc35247fbbd285892a90ab06ebb8f74b8a6329
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - kconfig-devel
    - ki18n-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
