name       : libksane
version    : 21.08.1
release    : 43
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/libksane-21.08.1.tar.xz : 7d78ac9fc3c97235a698c6993044c3d8851e413dc7207d4dd6cae2cf5cd39cf4
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - kconfig-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
