name       : libksane
version    : 23.04.3
release    : 58
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/libksane-23.04.3.tar.xz : 26c3cf34a741bb2b50cfdbbc20a5dffd58fc7b7ab2580a356bd047ccf2ccba42
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - kconfig-devel
    - ksanecore-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
