name       : libksane
version    : 18.12.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/libksane-18.12.0.tar.xz : b217a1b6557cf26c07a8aa34fca5d2dc140bec4ad768176a4d32ba4366f4bded
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - kconfig-devel
    - ki18n-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
