name       : libksane
version    : 22.08.3
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/libksane-22.08.3.tar.xz : f9e9955e322d79c0dab990197ea2de576a1c25526741574d42c1ab1a2ad22e8b
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - kconfig-devel
    - ksanecore-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
