name       : libksane
version    : 19.08.3
release    : 18
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/libksane-19.08.3.tar.xz : 97808ced0a0c6800c31fa8e810d2a00a3dbda410ed6691e114173b0412b94f93
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - kconfig-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
