name       : libksane
version    : 20.12.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/libksane-20.12.0.tar.xz : 5bc01f05a55e1d97a45352b9f708af25e09324618836b8a60c59fa2c6e77d066
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - kconfig-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
