name       : libksane
version    : 23.04.2
release    : 57
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/libksane-23.04.2.tar.xz : 40744fc514de08de967f39411ed92dad89c803c323f33a25bc5962eb8c3f66f7
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - kconfig-devel
    - ksanecore-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
