name       : libksane
version    : 20.08.3
release    : 32
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/libksane-20.08.3.tar.xz : 40264a1ddb73ea886ec4b0c2498ad607f0bbc6ddf23499badde1993077b54c34
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - kconfig-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
