name       : libksane
version    : 21.08.2
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/libksane-21.08.2.tar.xz : d2dfb261a92e783b03bd02aa138426d757727205fa5359ac24a7328e812b9324
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - kconfig-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
