name       : libksane
version    : 20.04.1
release    : 26
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/libksane-20.04.1.tar.xz : e88d173d5f46049fad345caa308e1041ef619317df9783c84d30c2b35379eb0a
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - kconfig-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
