name       : libksane
version    : 18.12.2
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/libksane-18.12.2.tar.xz : 13001e84af522a8323c2d1c2769683958ed112a87b1d375f95d66e57a1c1f8d3
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - kconfig-devel
    - ki18n-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
