name       : libksane
version    : 20.08.1
release    : 30
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/libksane-20.08.1.tar.xz : 0d8717ad004a2480aea232d9a2317b4d1cc4678d53f0176bdaeb411eedd19dbe
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - kconfig-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
