name       : libksane
version    : 19.08.2
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/libksane-19.08.2.tar.xz : 97e05423f4a9205b9db0bbce5111615d6bf8e8d53a391d3398275babccd91aa0
license    : GPL-2.0-or-later
component  : desktop.library
summary    : SANE Library interface for KDE
description: |
    libKSane is an image scanning library that provides a QWidget containing all the logic needed to interface with a scanner.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - kconfig-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
rundeps    :
    - sane-backends
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
